# ==============================================================================
# ECONOMETRICS LLM LAB: FROM REAL DATA TO STATISTICAL INFERENCE
# ==============================================================================
#
# DATA
# ----
# We use wage1 from the wooldridge package: 526 observations from the 1976
# US Current Population Survey. These are real, observational, cross-sectional
# data. See ?wooldridge::wage1 for sources and variable definitions.
#
# MAIN QUESTION
# -------------
# How are wages related to education, and how much uncertainty is there in the
# patterns we estimate from a sample?
#
# IMPORTANT
# ---------
# An association is not automatically a causal effect. These data were not
# generated by a randomized experiment.
#
# HOW TO USE AN LLM IN THIS LAB
# -----------------------------
# For every task:
#   1. Give the LLM the task, relevant variable names, and the requirement to
#      use tidyverse pipes and ggplot2.
#   2. Ask for one small code block at a time.
#   3. Run the code. Read errors, warnings, tables, and axis labels.
#   4. Ask the LLM to explain each function and the statistical result.
#   5. Revise weak code or interpretations yourself.
#
# Submit for each task:
#   - runnable R code;
#   - the main numerical or graphical result;
#   - a one- or two-sentence interpretation in your own words;
#   - the most useful prompt you gave the LLM.
#
# Suggested first prompt:
# "Act as an R tutor. Help me solve one task at a time using tidyverse pipes
# and ggplot2. Explain every important choice. Do not invent output, and do not
# use causal language for observational data."
#
# If needed, install the packages ONCE by removing the # on the next line:
# install.packages(c("tidyverse", "wooldridge"))

library(tidyverse)
library(wooldridge)

data("wage1", package = "wooldridge")

wage_data <- wage1 |>
  as_tibble()

set.seed(3081)


# ==============================================================================
# SESSION 1 (45 MINUTES): UNDERSTAND AND DESCRIBE REAL ECONOMIC DATA
# ==============================================================================

# ---------------------------------------------------------------------------- --
# Task 1 — Data-generating process and data structure (about 5 minutes)
# ---------------------------------------------------------------------------- --
# a. Open the documentation with ?wage1.
# b. Use tidyverse-friendly commands to display the dimensions, variable names,
#    and the first six rows of wage_data.
# c. Classify the data as cross-sectional, time-series, or panel data.
# d. Explain why a wage comparison in these data is observational rather than
#    experimental.
# e. Identify the units of observation and the units of wage, educ, exper, and
#    tenure.
#
# LLM challenge: Ask the LLM what it would need to know before interpreting a
# coefficient on educ as a causal return to education.


# ---------------------------------------------------------------------------- --
# Task 2 — Build an analysis dataset with a pipe (about 8 minutes)
# ---------------------------------------------------------------------------- --
# Starting from wage_data, create an object named analysis_data that:
#   - keeps wage, educ, exper, tenure, female, nonwhite, married, and numdep;
#   - creates log_wage = log(wage);
#   - creates gender as a factor with labels "Man" and "Woman";
#   - creates degree as a factor equal to "College degree" when educ >= 16 and
#     "No college degree" otherwise;
#   - checks for missing values and non-positive wages.
#
# Your code should use a pipe and the verbs select(), mutate(), and summarise().
# Explain why log(wage) is defined only for positive wages.


# ---------------------------------------------------------------------------- --
# Task 3 — Describe the wage distribution (about 10 minutes)
# ---------------------------------------------------------------------------- --
# Using analysis_data:
# a. Produce one tidy summary row containing n, mean, median, standard deviation,
#    interquartile range, minimum, and maximum for wage.
# b. Create a histogram of wage with an informative title and axis labels.
# c. Create a histogram of log_wage using the same graphical style.
# d. Compare the two distributions. Which is more symmetric? Where do you see
#    evidence of skewness or possible outliers?
#
# LLM challenge: Ask the LLM why the mean wage may exceed the median wage. Check
# its explanation against your plots rather than accepting it automatically.


# ---------------------------------------------------------------------------- --
# Task 4 — Conditional means and variation (about 10 minutes)
# ---------------------------------------------------------------------------- --
# a. Group the data by gender and calculate n, mean_wage, sd_wage, mean_educ,
#    and mean_log_wage.
# b. Make a boxplot of wage by gender and overlay the group means as points.
# c. In plain language, interpret E(wage | gender) as a conditional mean.
# d. Explain why a difference in conditional means does not by itself establish
#    discrimination or a causal gender effect.
#
# Stretch question: Calculate the overall variance of wage. Then ask your LLM
# how the law of total variance relates overall wage variation to within-gender
# and between-gender variation. You do not need to derive the formula in R.


# ---------------------------------------------------------------------------- --
# Task 5 — Covariance, correlation, slopes, and logarithms (about 12 minutes)
# ---------------------------------------------------------------------------- --
# a. Calculate cov(wage, educ), cor(wage, educ), and cor(log_wage, educ).
# b. Create a scatterplot of wage against educ, add jitter to reduce overplotting,
#    and add a straight fitted line using geom_smooth(method = "lm").
# c. Repeat with log_wage on the vertical axis.
# d. Explain the sign of the covariance and correlations. Why is correlation
#    easier to compare across variables than covariance?
# e. Without claiming causality, explain what the slope of the log-wage line
#    would describe. Connect your answer to the approximation
#    100 * change in log(wage) = approximate percentage change in wage.
#
# End-of-session checkpoint: Write one economic pattern you found, one source of
# uncertainty, and one reason the pattern should not yet be called causal.


# ==============================================================================
# SESSION 2 (45 MINUTES): SAMPLING, CONFIDENCE INTERVALS, AND TESTING
# ==============================================================================

# For the simulation tasks, treat the 526 observed workers as a finite
# "population". Sampling with replacement then shows what repeated random
# samples from this empirical population would look like.

# ---------------------------------------------------------------------------- --
# Task 6 — Sampling distributions and the central limit theorem (15 minutes)
# ---------------------------------------------------------------------------- --
# a. Calculate the mean wage in the full dataset; call it population_mean.
# b. Draw 2,000 samples WITH replacement for each sample size n = 20 and n = 100.
# c. Calculate the mean wage in every sample. Store the results in a tidy tibble
#    named sampling_results with columns sample_size, repetition, and sample_mean.
# d. Plot the sampling distributions in two facets with a vertical line at
#    population_mean.
# e. For each sample size, calculate:
#      - the average of the 2,000 sample means;
#      - the standard deviation of the sample means (simulated standard error);
#      - the theoretical standard error sd(wage) / sqrt(n).
# f. Explain how the center, spread, and shape change as n rises from 20 to 100.
#
# Suggested LLM prompt:
# "Use tidyr::crossing(), purrr::map2_dbl(), sample(), and summarise() to build
# this simulation. Explain why replace = TRUE is required and why set.seed()
# matters."


# ---------------------------------------------------------------------------- --
# Task 7 — Construct confidence intervals yourself (10 minutes)
# ---------------------------------------------------------------------------- --
# For each gender, construct a 95% confidence interval for the population mean
# wage using:
#
#   sample mean +/- t critical value * sample standard deviation / sqrt(n)
#
# Requirements:
#   - use group_by(gender) and summarise();
#   - obtain the critical value with qt(0.975, df = n - 1);
#   - return n, mean_wage, standard_error, lower, and upper;
#   - state what the interval does and does not mean.
#
# LLM audit: If the LLM says there is a 95% probability that the fixed population
# mean lies inside the interval you already calculated, ask it to correct that
# frequentist interpretation.


# ---------------------------------------------------------------------------- --
# Task 8 — Test a difference in population means (10 minutes)
# ---------------------------------------------------------------------------- --
# Use a Welch two-sample t-test to investigate whether mean wage differs between
# women and men:
#
#   H0: mean_wage_women - mean_wage_men = 0
#   H1: mean_wage_women - mean_wage_men != 0
#
# a. Run the test with t.test(). Do not assume equal population variances.
# b. Extract and report the estimated group means, difference in sample means,
#    t statistic, degrees of freedom, p-value, and 95% confidence interval.
# c. State the decision at alpha = 0.05 and interpret it in context.
# d. Distinguish statistical significance, economic importance, and causality.
# e. Name at least two omitted variables that could help explain the raw gap.
#
# LLM challenge: Ask the LLM to check whether the sign of the reported difference
# is consistent with the order of the factor levels and the displayed means.


# ---------------------------------------------------------------------------- --
# Task 9 — A first econometric model and an LLM quality audit (10 minutes)
# ---------------------------------------------------------------------------- --
# Estimate the descriptive model:
#
#   log(wage_i) = beta_1 + beta_2 educ_i + e_i
#
# a. Fit the model with lm() and inspect summary().
# b. Make a tidy coefficient table from the model output.
# c. Interpret beta_2 as both an approximate and an exact percentage wage
#    difference associated with one additional year of education. For the exact
#    transformation use 100 * (exp(beta_2) - 1).
# d. Plot the data and fitted line.
# e. Give two reasons beta_2 should not automatically be interpreted as the
#    causal return to education.
#
# FINAL LLM AUDIT
# Ask your LLM to evaluate these four claims and correct every false or incomplete
# claim. Support the corrections with your own output.
#
#   1. "A small p-value proves that education causes higher wages."
#   2. "A 95% confidence interval contains 95% of individual wages."
#   3. "A larger sample makes the estimator less biased."
#   4. "Because log(wage) is used, beta_2 is always exactly a percentage change."
#
# Exit ticket: Write three sentences separating (i) the pattern in this sample,
# (ii) uncertainty about the corresponding population relationship, and
# (iii) what additional design or assumptions would be needed for causality.

